version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

orbs:
  azure-acr: circleci/azure-acr@x.y.z # Use the Azure ACR orb in your config

workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          login-server-name: ovaas.azurecr.io
          registry-name: ovaas
          repo: grpc-todolist