name: Enovy - Build and push docker image

on:
  push:
    branches:
      - master
    paths:
      - 'enovy/*'
      - '.github/workflows/enovy-build.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./client -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/grpc-todo-enovy:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/grpc-todo-enovy:${{ github.sha }}
        